In [1]:
#Import Pandas and read csv file
import pandas
df = pandas.read_csv("Business_Licenses.csv")
df.head()

/Users/gallasteguicrino/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (9,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ID,LICENSE ID,ACCOUNT NUMBER,SITE NUMBER,LEGAL NAME,DOING BUSINESS AS NAME,ADDRESS,CITY,STATE,ZIP CODE,...,LICENSE TERM START DATE,LICENSE TERM EXPIRATION DATE,LICENSE APPROVED FOR ISSUANCE,DATE ISSUED,LICENSE STATUS,LICENSE STATUS CHANGE DATE,SSA,LATITUDE,LONGITUDE,LOCATION
0,22308-20060816,1723393,29481,1,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,3741 S PULASKI RD 1,CHICAGO,IL,60623,...,08/16/2006,08/15/2007,08/10/2006,08/11/2006,AAI,NaN,NaN,41.825320,-87.723960,"(41.82531992987547, -87.72395999659746)"
1,1620668-20160516,2455262,295026,1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,558 W ROOSEVELT RD,CHICAGO,IL,60607,...,05/16/2016,05/15/2018,05/18/2016,08/30/2016,AAI,NaN,NaN,41.867339,-87.641590,"(41.86733856638269, -87.64159005699716)"
2,2368602-20160616,2460909,291461,3,"PROJECT: VISION , INC.","PROJECT : VISION , INC",2301 S ARCHER AVE 1 1,CHICAGO,IL,60616,...,06/16/2016,06/15/2017,06/21/2016,06/22/2016,AAC,08/30/2016,NaN,41.850843,-87.638734,"(41.85084294374687, -87.63873424399071)"
3,2060891-20141016,2353257,357247,1,FOLASHADE'S CLEANING SERVICE INC.,FOLASHADE'S CLEANING SERVICE INC.,1965 BERNICE RD 1 1SW,LANSING,IL,60438,...,10/16/2014,10/15/2016,04/01/2016,04/01/2016,AAI,NaN,38.0,41.951316,-87.678586,"(41.95131555606832, -87.67858578019546)"
4,1144216-20070516,1804790,147,63,WALGREEN CO.,Walgreens # 05192,9148 S COMMERCIAL AVE 1ST,CHICAGO,IL,60617,...,05/16/2007,05/15/2008,05/10/2007,05/11/2007,AAI,NaN,5.0,41.728622,-87.551366,"(41.72862173556932, -87.55136646594693)"

In [2]:
df.shape

(957634, 34)

In [3]:
# List all variables as some were omited above. 
list(df)

['ID',
 'LICENSE ID',
 'ACCOUNT NUMBER',
 'SITE NUMBER',
 'LEGAL NAME',
 'DOING BUSINESS AS NAME',
 'ADDRESS',
 'CITY',
 'STATE',
 'ZIP CODE',
 'WARD',
 'PRECINCT',
 'WARD PRECINCT',
 'POLICE DISTRICT',
 'LICENSE CODE',
 'LICENSE DESCRIPTION',
 'BUSINESS ACTIVITY ID',
 'BUSINESS ACTIVITY',
 'LICENSE NUMBER',
 'APPLICATION TYPE',
 'APPLICATION CREATED DATE',
 'APPLICATION REQUIREMENTS COMPLETE',
 'PAYMENT DATE',
 'CONDITIONAL APPROVAL',
 'LICENSE TERM START DATE',
 'LICENSE TERM EXPIRATION DATE',
 'LICENSE APPROVED FOR ISSUANCE',
 'DATE ISSUED',
 'LICENSE STATUS',
 'LICENSE STATUS CHANGE DATE',
 'SSA',
 'LATITUDE',
 'LONGITUDE',
 'LOCATION']

In [4]:
# Create new dataframe with the variables we'll use. 
df_1 = df[["LEGAL NAME", 'DOING BUSINESS AS NAME', "LICENSE CODE", "CITY", "WARD", "ZIP CODE", "DATE ISSUED", "LATITUDE", "LONGITUDE", "LOCATION"]]
df_1.head()

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE,LOCATION
0,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,1010,CHICAGO,14.0,60623,08/11/2006,41.825320,-87.723960,"(41.82531992987547, -87.72395999659746)"
1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,1010,CHICAGO,25.0,60607,08/30/2016,41.867339,-87.641590,"(41.86733856638269, -87.64159005699716)"
2,"PROJECT: VISION , INC.","PROJECT : VISION , INC",1625,CHICAGO,25.0,60616,06/22/2016,41.850843,-87.638734,"(41.85084294374687, -87.63873424399071)"
3,FOLASHADE'S CLEANING SERVICE INC.,FOLASHADE'S CLEANING SERVICE INC.,1010,LANSING,NaN,60438,04/01/2016,41.951316,-87.678586,"(41.95131555606832, -87.67858578019546)"
4,WALGREEN CO.,Walgreens # 05192,1010,CHICAGO,10.0,60617,05/11/2007,41.728622,-87.551366,"(41.72862173556932, -87.55136646594693)"

In [5]:
# Flter by city (Chicago) 
df_2 = df_1.query('CITY == "CHICAGO"')
df_2.head()

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE,LOCATION
0,BELL OIL TERMINAL INC,Bell Oil Terminal LLC,1010,CHICAGO,14.0,60623,08/11/2006,41.825320,-87.723960,"(41.82531992987547, -87.72395999659746)"
1,BUCCI BIG & TALL INC.,BUCCI BIG & TALL INC.,1010,CHICAGO,25.0,60607,08/30/2016,41.867339,-87.641590,"(41.86733856638269, -87.64159005699716)"
2,"PROJECT: VISION , INC.","PROJECT : VISION , INC",1625,CHICAGO,25.0,60616,06/22/2016,41.850843,-87.638734,"(41.85084294374687, -87.63873424399071)"
4,WALGREEN CO.,Walgreens # 05192,1010,CHICAGO,10.0,60617,05/11/2007,41.728622,-87.551366,"(41.72862173556932, -87.55136646594693)"
5,"BURKS HEATING AND COOLING SOLUTIONS, LLC","BURKS HEATING AND COOLING SOLUTIONS, LLC",4404,CHICAGO,15.0,60636,08/30/2016,41.789617,-87.669472,"(41.78961679000226, -87.66947199630827)"

In [6]:
df_2.shape

(887891, 10)

In [12]:
# FIlter by license code
df_3 = df_2[df_2['LICENSE CODE'] == 1006]
df_3.shape

(141713, 10)

In [13]:
df_3

,LEGAL NAME,DOING BUSINESS AS NAME,LICENSE CODE,CITY,WARD,ZIP CODE,DATE ISSUED,LATITUDE,LONGITUDE,LOCATION
11,"OLD TOWN OIL, LLC","OLD TOWN OIL, LLC",1006,CHICAGO,27.0,60610,08/30/2016,41.910408,-87.634540,"(41.91040819050054, -87.63454009171004)"
35,MO MO HOUSE CORP.,NEPAL HOUSE - NAPALESE CUISINE,1006,CHICAGO,50.0,60659,08/30/2016,41.997535,-87.694822,"(41.99753534020119, -87.69482177020934)"
44,THIRD DEGREE CHICAGO LLC,STUDIO III,1006,CHICAGO,42.0,60654,01/17/2017,NaN,NaN,NaN
47,"VIENNA SERVICES, INC.",CAFE VIENNA,1006,CHICAGO,43.0,60614,08/31/2016,41.928487,-87.642044,"(41.928487374216466, -87.64204435669477)"
63,STARBUCKS CORPORATION,STARBUCKS COFFEE #216,1006,CHICAGO,42.0,60611,03/18/2015,41.893341,-87.617589,"(41.893341296312244, -87.61758915120579)"
92,GENERAL GROWTH MANAGEMENT INC.,GENERAL GROWTH MANAGEMENT INC,1006,CHICAGO,42.0,60606,08/31/2016,41.883498,-87.637200,"(41.88349824310264, -87.63720027259416)"
107,STARBUCKS CORPORATION,STARBUCKS COFFEE #9426,1006,CHICAGO,1.0,60642,03/18/2015,41.891770,-87.658605,"(41.89176977820589, -87.65860461424934)"
108,STARBUCKS CORPORATION,STARBUCKS COFFEE #2510,1006,CHICAGO,42.0,60610,03/18/2015,41.889683,-87.637121,"(41.889682960687374, -87.63712095614753)"
111,KURIAN FOODS INC.,AL'S BEEF,1006,CHICAGO,42.0,60604,08/31/2016,41.878674,-87.626242,"(41.878674348181335, -87.62624229534441)"
131,STARBUCKS CORPORATION,STARBUCKS #17743,1006,CHICAGO,40.0,60659,03/18/2015,41.992587,-87.689862,"(41.99258748774938, -87.6898621543762)"
141,FG TRADING INC.,24 SEVEN FOOD MART,1006,CHICAGO,46.0,60613,08/31/2016,41.961667,-87.649761,"(41.96166713685557, -87.64976056950601)"
218,"SRJ ENTERPRISES, INC.",7-ELEVEN,1006,CHICAGO,42.0,60606,08/31/2016,41.879473,-87.635807,"(41.87947279717996, -87.63580748102805)"
224,"ROXANNE FOOD MART, INC.","ROXANNE FOOD MART, INC.",1006,CHICAGO,20.0,60621,08/31/2016,41.792483,-87.644966,"(41.792482647024215, -87.6449659047179)"
227,THOMAS I. YI,"HOUND DOG, BURGER & TERIYAKI RESTAURANT",1006,CHICAGO,26.0,60612,08/31/2016,41.890595,-87.684048,"(41.89059496364399, -87.68404796959847)"
237,LUFRAN INC,PEPE'S MEXICAN RESTAURANT,1006,CHICAGO,6.0,60619,08/31/2016,41.750921,-87.619937,"(41.75092109529809, -87.61993681854683)"
244,STARBUCKS CORPORATION,STARBUCKS COFFEE #22949,1006,CHICAGO,42.0,60604,05/15/2012,41.885802,-87.624660,"(41.885801546318, -87.62465977106316)"
245,STARBUCKS CORPORATION,STARBUCKS COFFEE #15683,1006,CHICAGO,42.0,60602,03/18/2015,41.882288,-87.624518,"(41.882288176801794, -87.62451779096743)"
311,"Food For Thought Cafe at the Adler, Ltd.",Galileo's,1006,CHICAGO,4.0,60605,08/31/2016,41.865732,-87.619669,"(41.865732312266495, -87.61966863731983)"
323,"MINA 4 ENTERPRISE GROUP INC.,",7-ELEVEN #33496C,1006,CHICAGO,4.0,60605,08/31/2016,41.875011,-87.627475,"(41.87501057316559, -87.627474631035)"
348,"LOYOLA FOOD MART, INC.","LOYOLA FOOD MART, INC.",1006,CHICAGO,49.0,60626,08/31/2016,42.000720,-87.660656,"(42.000720124073766, -87.66065603221865)"
366,"CANALU, LLC",DINOTTO PIZZERIA (CATERING),1006,CHICAGO,27.0,60610,08/31/2016,41.910627,-87.634547,"(41.91062675138243, -87.63454715819464)"
402,"GO! GROCER PINE GROVE, INC.",GO! GROCER,1006,CHICAGO,46.0,60613,08/31/2016,41.953774,-87.648061,"(41.953774064116395, -87.64806067621346)"
410,"LA TERRAZA GALLO CORP.,",LA TERRAZA GALLO,1006,CHICAGO,12.0,60623,08/31/2016,41.851745,-87.698823,"(41.85174454712867, -87.69882322090157)"
442,LA MICHOACANA DE PONCITLAN INC.,LA MICHOACANA DE PONCITLAN,1006,CHICAGO,14.0,60632,08/31/2016,41.799082,-87.703863,"(41.79908205644847, -87.70386302302413)"
498,"HEALTHY ORGANIC KIDS, INC.",HEALTHY ORGANIC KIDS,1006,CHICAGO,27.0,60642,08/31/2016,41.891026,-87.652005,"(41.89102614763669, -87.65200458816506)"
548,YUN CHIU YU,CHINA SNACK,1006,CHICAGO,12.0,60623,07/19/2004,41.851709,-87.701519,"(41.85170859051169, -87.70151949091587)"
595,"LA BAGUETTE NORTH, INC.",LA BAGUETTE NORTH,1006,CHICAGO,49.0,60626,11/18/2003,42.009193,-87.673860,"(42.009192621225374, -87.67386024200934)"
596,PESTO 59 INC.,AVALON BAR & GRILL,1006,CHICAGO,41.0,60656,08/31/2016,41.977955,-87.846320,"(41.97795546524052, -87.84631988834286)"
648,STARBUCKS CORPORATION,Starbucks Coffee #22423,1006,CHICAGO,2.0,60610,03/18/2015,41.904831,-87.635028,"(41.90483115028203, -87.63502774510842)"
655,"DARIA EXPORTS, INC.",TARBOUSH MEDITERRANEAN GRILL,1006,CHICAGO,32.0,60622,08/31/2016,41.910734,-87.668093,"(41.9107340942111, -87.66809336341993)"
...,...,...,...,...,...,...,...,...,...,...
957570,FARZAND INC,7-ELEVEN,1006,CHICAGO,18.0,60652,04/18/2006,41.742131,-87.721824,"(41.742130554061674, -87.72182410032978)"
957571,"PAIRED WINE COMPANY CHICAGO, INC.",PAIRED,1006,CHICAGO,44.0,60657,06/24/2015,41.942603,-87.649207,"(41.942602833224626, -87.6492070020833)"
957573,"THE HEARTY BOYS CATERERS, INC.",SPRITZ BURGER,1006,CHICAGO,46.0,60613,02/13/2007,41.951801,-87.649477,"(41.951800759558395, -87.64947747658742)"
957575,"MINHAZ, INC.",GROCERY STORE MARTINEZ MINIMART,1006,CHICAGO,31.0,60639,01/16/2007,41.924518,-87.733113,"(41.924518490422905, -87.73311251466045)"
957576,EL TACONAZO LA FIESTA INC.,EL TACONAZO LA FIESTA INC.,1006,CHICAGO,30.0,60639,05/12/2016,41.929495,-87.766330,"(41.92949530063107, -87.7663302984316)"
957577,BONYS FOOD INC.,BONYS FOOD MART,1006,CHICAGO,25.0,60608,09/02/2015,41.855279,-87.653280,"(41.85527879701619, -87.65327978679655)"
957578,JOHN C HALLE,SALT & PEPPER DINER,1006,CHICAGO,44.0,60657,02/18/2015,41.946637,-87.655893,"(41.946637015990326, -87.65589270770178)"
957581,BENITO GUZMAN,JOE'S BREAKFAST & GRILL,1006,CHICAGO,20.0,60609,04/24/2015,41.801563,-87.654917,"(41.80156348207917, -87.65491674033504)"
957582,"HALSTED GROCERIES, INC.","HALSTED GROCERIES, INC.",1006,CHICAGO,6.0,60621,10/13/2010,41.765296,-87.644269,"(41.7652957077341, -87.64426896091481)"
957583,"HORIZON VIEW RESTAURANT & BUFFET, INC",RELAXING RESTAURANT,1006,CHICAGO,35.0,60625,04/17/2002,41.968390,-87.724448,"(41.968390431264375, -87.72444785924317)"
957585,ROSALIA BRITO,LAKE BREEZE RESTAURANT,1006,CHICAGO,48.0,60660,08/12/2011,41.990151,-87.658965,"(41.9901513640645, -87.65896490548317)"
957588,BOB & JACK'S PIZZA INC,BOB & JACK'S PIZZA INC,1006,CHICAGO,10.0,60617,07/23/2008,41.708706,-87.535435,"(41.70870572375043, -87.53543488600923)"
957591,75 EAST WACKER DRIVE INC,BACINO'S ON WACKER,1006,CHICAGO,42.0,60601,12/13/2002,41.887862,-87.625413,"(41.88786189172989, -87.62541304135654)"
957593,BRYN MAWR RESTAURANT CORP.,NOOKIES CAFE & RESTAURANT,1006,CHICAGO,48.0,60660,09/01/2011,41.983766,-87.658112,"(41.98376648449397, -87.65811162403335)"
957595,THE SALVATION ARMY,THE SALVATION ARMY,1006,CHICAGO,28.0,60607,09/13/2004,41.880086,-87.665054,"(41.88008566659281, -87.66505441566734)"
957596,"THE SIDE WITH THE BUTTER ON IT INDUSTRIES, INC.",MFK,1006,CHICAGO,44.0,60614,04/04/2011,41.932995,-87.640640,"(41.93299476122033, -87.64064047605578)"
957600,FRESH MART FOODS INC.,FRESH MART FOODS,1006,CHICAGO,6.0,60619,02/05/2009,41.743923,-87.614687,"(41.743922906387006, -87.61468748613066)"
957604,M. V. ONE INCORPORATED,MR G SUPPER CLUB,1006,CHICAGO,21.0,60620,08/14/2007,41.735691,-87.662328,"(41.735691078577986, -87.66232767688463)"
957610,"CRU CAFE & WINE BAR, LIMITED",CRU CAFE & WINE BAR,1006,CHICAGO,2.0,60611,12/09/2003,41.899173,-87.627017,"(41.89917306355854, -87.62701738238093)"
957611,DIVERSEY RIVER LOUNGE INC,DIVERSEY RIVER BOWL LOUNGE,1006,CHICAGO,1.0,60647,10/26/2004,41.932110,-87.683616,"(41.93210985510181, -87.68361585249846)"
957615,"KPOKOS IV, INC.,",Yolk Cafe,1006,CHICAGO,42.0,60611,08/10/2010,41.892525,-87.618134,"(41.89252476076749, -87.61813382654785)"
957617,"EFIE'S CANTEEN, INC.",Cubs Bar & Grill,1006,CHICAGO,41.0,60666,12/23/2015,42.008536,-87.914428,"(42.008536400868735, -87.91442843927047)"
957618,IMRAN SARIO,T J SUB,1006,CHICAGO,24.0,60623,09/28/2005,41.858824,-87.734591,"(41.85882397025515, -87.73459109692567)"
957620,7-12 FOOD MART INC,O. G'S FOOD & LIQUOR,1006,CHICAGO,36.0,60707,06/16/2004,41.930996,-87.795328,"(41.930995823266166, -87.79532809968535)"
957622,RUBEN MORA & GRACIELA TELLO,MINI AZTECA,1006,CHICAGO,49.0,60626,10/11/2013,42.007331,-87.673725,"(42.007331192630126, -87.67372465116485)"
957626,"NOBLE TREE, LLC",NOBLE TREE,1006,CHICAGO,43.0,60614,05/20/2011,41.926706,-87.641318,"(41.92670566610603, -87.64131782303711)"
957628,"MIGUEL SILVA, INC.",CARNICERIA GUANJUATO #3,1006,CHICAGO,2.0,60622,04/18/2003,41.908115,-87.667764,"(41.90811537393747, -87.66776383350285)"
957630,"CHICAGO FOOD CLUB, LLC",CHICAGO FOOD CLUB,1006,CHICAGO,9.0,60628,04/21/2015,41.687568,-87.621110,"(41.687568449316295, -87.62111015081878)"
957631,LUCKY LIAO INC.,CHINA SPRING,1006,CHICAGO,49.0,60626,10/03/2008,42.009193,-87.673860,"(42.009192621225374, -87.67386024200934)"
957633,SHIRLEY PEEPLES,PEEPLES TACO'S,1006,CHICAGO,29.0,60651,10/25/2004,41.894838,-87.774089,"(41.89483794336363, -87.77408918515034)"